[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  [[plugins]]
  package = "@sentry/netlify-build-plugin"

  [plugins.inputs]
    sentryOrg = "your org slug"
    sentryProject = "your project slug"